### PR TITLE
chore: remove old Node.js versions

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by kzc** [comment]
Those old platforms are still supported.

**Comment by DanielRuf** [comment]
> Those old platforms are still supported.

Not officially and there are no new updates, especially security updates. They all reached their EOL.

**Comment by kzc** [comment]
People are still using those versions despite their official status. It doesn't cost us anything.

**Comment by DanielRuf** [comment]
> People are still using those versions despite their official status. It doesn't cost us anything.

I see it different as many dependencies are just compatible with 6+ now and we should not support old and insecure versions. Same change was accepted in other (big) projects.

But ok, if this is fine for you. More to test and possibly tests will break in the foreseeable future when dependencies are changes.

**Pull request closed without merging**
