### PR TITLE
Do not mangle computed properties

### LINKED ISSUE #93: Mangling computed properties from symbols when it should not
When mangling properties, computed properties from symbols should not be mangled.

**Minimal exemple**
running ``terser --mangle-props test.js`` with
```javascript
const mySymbol = Symbol('foo');
const myObject = {
    [mySymbol]: 'bar'
}
console.log(myObject[mySymbol]);
```
gives
```javascript
const mySymbol=Symbol("foo");
const myObject={o:"bar"};
console.log(myObject[mySymbol]);
```
instead of
```javascript
const mySymbol=Symbol("foo");
const myObject={[mySymbol]:"bar"};
console.log(myObject[mySymbol]);
```

### PR DESCRIPTION
**Pull request by PaulBlanche**
should fix #93

### CODE REVIEW

**Comment by kzc** [comment]
Please squash into a single commit with comment:
```
do not mangle computed properties

fixes #93
```

**Comment by kzc** [comment]
Looks like this PR needs a rebase due to recent formatting changes in `lib/propmangle.js`.

**Comment by kzc** [comment]
Other than the suggestions above, this PR is sound. If anyone wants to rebase and resubmit a new PR, feel free.

**Comment by kzc** [comment]
Discovered a bug in the suggested patch: https://github.com/fabiosantoscode/terser/issues/93#issuecomment-421528524.

This PR is replaced with #110.

**Comment by fabiosantoscode** [comment]
Closed in https://github.com/fabiosantoscode/terser/pull/110

**Pull request closed without merging**
