### PR TITLE
chore: cache node_modules

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by kzc** [comment]
This is not necessary.

**Comment by DanielRuf** [comment]
Why not? This creates a build cache to speedup builds. As alternative there is also a cache for npm.

**Comment by kzc** [comment]
The dependency versions are not locked down. It's fine as is.

**Comment by DanielRuf** [comment]
> The dependency versions are not locked down. It's fine as is.

This has nothing to do with this.
Take a look at the build caches of CircleCI and what they are for.

https://docs.travis-ci.com/user/caching/

The cache is automatically updated if there are changes.

**Comment by Martii** [comment]
@kzc

So let me get this right... you don't want to potentially improve build times for all deps and their sub-deps with some sort of caching? Have you tested this for this project *(if so cite please)*? Seems to me that spending less time waiting, for example the most recent CI at https://travis-ci.org/fabiosantoscode/terser/builds/398969641?utm_source=github_status&utm_medium=notification, would be an improvement on human resources as well as automation.

So I think a good question is what do you mean that it's "not locked down"? Do you mean *terser*'s dependencies *(all of them most likely)* or do you mean their sub-dependencies? Every project I've observed usually tries to improve the time spent with some sort of caching. They usually get a drastic change in build times as do we in other build arenas. There are some known issues with Homebrew that I've interacted with but I don't think that is utilized here.

@DanielRuf 
Perhaps doing a full dependency tree for each *node* version would help improve the understanding here. e.g. show which dependency versions are reused through each session of CI even in parallel builds.

**Comment by DanielRuf** [comment]
> you don't want

I guess you mean
> you want to

**Comment by DanielRuf** [comment]
Homebrew is used on macOS X and not here and not for CI in most cases.

Travis CI loads the cache, runs `npm install` over it, compares the changes of `node_modules` and creates a new cache if there are changes.

**Comment by DanielRuf** [comment]
This is what I mean with locked down, the cache just preloads node_modules.

As example: think about the same with your local clone. It has node_modules. If there is a change in the dependency tree or a change in package.json or package-lock.json in general, a `npm install` with your current node_modules directory will update the relevant dependencies and overwrite / change the needed files.

**Comment by DanielRuf** [comment]
Testing this locally is easy: use an older clone with prefilled node_modules, run `npm install` to update the dependencies and compare it to the same clone without node_modules / with empty node_modules.

**Comment by DanielRuf** [comment]
Travis CI automatically creates different cache "branches" for each Node.js version.

The 8-versions get something like cache-node8 and 10 uses cache-10 or similar. At least their caching system already does some optimizations.

In general `npm install` outputs the whole dependency tree after a clean / fresh install.

**Comment by Martii** [comment]
@DanielRuf 
Without getting too involved into your very large misunderstanding here...  the @kzc heading means it's not directed to you @DanielRuf.  So **yes** I do mean "You *(as in kzc)* don't want to potentially improve build times"... by closing this PR without any type of useful discussion.

I also know caching either at the CI level or further down the line helps improve build times since it doesn't have to download even in a parallel build. You, @DanielRuf , need to sell your point to @kzc ... I already know it improves development time as I've already contributed to a few projects where a beast such as this is implemented. So please make sure you pay attention to who is being addressed. So go through your comments and **readdress (or delete) them to the proper person** instead of myself. Thanks and don't forget to read things a few times so you don't comment at the wrong person. :)

I would suggest at least a dependency tree for @kzc , showing the dependencies that won't need to be redownloaded *(for each node version listed at https://github.com/fabiosantoscode/terser/blob/226c0871be3675c5fc9a8b38d10fc5f0428f266d/.travis.yml#L3-L8)* since they would be cached, and he'll understand better... unless he has an ulterior motive for not doing something like this... in which case it should be better explained.

Ex.
* https://github.com/fabiosantoscode/terser/pull/73#issuecomment-402604571 You didn't need to address this because it wasn't addressed to you. Your guess was out of context.
* https://github.com/fabiosantoscode/terser/pull/73#issuecomment-402604788 I'm completely aware of macOS, and at least Linux, with brew. Again you didn't need to respond to this as I already know this... and you are partially correct. I also know this project hasn't mentioned this recently so it's highly unlikely that brew of any flavor is available or needed for this project since *npm* handles it just fine.
* https://github.com/fabiosantoscode/terser/pull/73#issuecomment-402605120 ... You didn't say it was locked down @kzc [did above](https://github.com/fabiosantoscode/terser/pull/73#issuecomment-401639856)... hence why my comment was addressed to @kzc not you.
* https://github.com/fabiosantoscode/terser/pull/73#issuecomment-402605348 and https://github.com/fabiosantoscode/terser/pull/73#issuecomment-402605706 ... that's what a dependency tree would show with its versions per node version... so we're on the same page with this comment. :+1: 

So remember again please... pay attention to whom a reply is being addressed to. It will make you able to sell your PR better and not confuse the heck out of everyone else. I figured it out rather quickly what your mistake was but not everyone may be up to speed with that.

**Comment by DanielRuf** [comment]
> Without getting too involved into your very large misunderstanding here... the @kzc heading means it's not directed to you @DanielRuf. So yes I do mean "You (as in kzc) don't want to potentially improve build times"... by closing this PR without any type of useful discussion.

Ah right sorry. My mobile phone did not show the first line, was probably the GitHub client or just oversaw it.

DX is very crucial and CI caches are very common and widely used, even in projects by facebook, airbnb and so on where I've also contributed to.

**Comment by DanielRuf** [comment]
Sorry, deleted the misleading comments. Was at 6am in the morning, probably too early.

**Comment by Martii** [comment]
@DanielRuf 

> was probably the GitHub client or just oversaw it.

Understandable... my usual browser doesn't show who closed this PR until I loaded a different one to see what happened. Perhaps a GH issue at GH that they don't know about just yet. :) Mornings can be rough on everyone. :smile_cat:

**Pull request closed without merging**
